@echo off
echo Parando processos Node...
taskkill /f /im node.exe 2>nul

echo Navegando para demandas-api...
cd demandas-api

echo Aplicando mudanças no banco...
npx prisma db push --force-reset

echo Regenerando cliente Prisma...
npx prisma generate

echo Iniciando servidor...
npm run dev
