import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { Demand, DemandId } from '../types/demand'
import type { TimelineEvent } from '../types/timeline'
import { useMasterDataStore } from './masterDataStore'

interface DemandState {
  items: Demand[]
  timeline: TimelineEvent[]
  isLoading: boolean
  lastSync: number
  add: (d: Omit<Demand, 'id' | 'createdAt' | 'updatedAt'>) => Promise<Demand>
  upsert: (d: Demand) => Promise<void>
  remove: (id: DemandId) => Promise<void>
  clear: () => void
  log: (e: Omit<TimelineEvent, 'id' | 'timestamp'>) => void
  syncFromApi: (force?: boolean) => Promise<void>
  syncTimeline: (demandaId: string) => Promise<void>
}

export const useDemandStore = create<DemandState>()(
  persist(
    (set, get) => ({
      items: [],
      timeline: [],
      isLoading: false,
      lastSync: 0,
      add: async (payload) => {
        console.log('🔍 DemandStore.add: Iniciando criação de demanda...')
        console.log('🔍 DemandStore.add: Payload recebido:', payload)
        
        function pad(num: number, size: number) {
          let s = String(num)
          while (s.length < size) s = '0' + s
          return s
        }
        
        function generateTicket(existing: Demand[]): string {
          const now = new Date()
          const y = now.getFullYear()
          const m = pad(now.getMonth() + 1, 2)
          const ym = `${y}${m}`
          const key = `ticket-seq-${ym}`
          let seq = 1
          try {
            const raw = localStorage.getItem(key)
            if (raw) seq = Number(raw) + 1
          } catch {}
          // garantir unicidade local
          let ticket = `DEM-${ym}-${pad(seq, 4)}`
          const has = (t: string) => existing.some((d) => (d.ticket || '').toUpperCase() === t.toUpperCase())
          while (has(ticket)) {
            seq += 1
            ticket = `DEM-${ym}-${pad(seq, 4)}`
          }
          localStorage.setItem(key, String(seq))
          return ticket
        }
        
        const now = new Date().toISOString()
        const existing = get().items
        
        // CORRIGIDO: Respeitar o ticket fornecido pelo usuário, ou gerar um novo se não fornecido
        const userProvidedTicket = payload.ticket && payload.ticket.trim() !== ''
        const ticket = userProvidedTicket ? payload.ticket.trim() : generateTicket(existing)
        
        console.log('🎫 TICKET DEBUG (Store):', {
          userInput: payload.ticket,
          userProvidedTicket,
          finalTicket: ticket,
          isAutoGenerated: !userProvidedTicket
        })
        
        // Filtrar apenas campos válidos para o backend (remover strings, manter apenas IDs)
        const apiPayload = {
          status: payload.status,
          ticket,
          analistaId: payload.analistaId,
          userId: payload.userId,
          solicitante: payload.solicitante,
          areaId: payload.areaId,
          tipoId: payload.tipoId,
          descricao: payload.descricao,
          tipoServicoId: payload.tipoServicoId,
          clienteId: payload.clienteId,
          contratoId: payload.contratoId,
          operadoraId: payload.operadoraId,
          produtoId: payload.produtoId,
          sistemaId: payload.sistemaId,
          ...(payload.sistemasIds && payload.sistemasIds.length ? { sistemasIds: payload.sistemasIds } : {}),
          dataInicio: payload.dataInicio,
          dataFinal: payload.dataFinal,
          qtdUsuarios: payload.qtdUsuarios,
          qtdRetornos: payload.qtdRetornos,
          qualidade: payload.qualidade,
          qtdClientesVinculados: payload.qtdClientesVinculados,
          usuariosEmpresa: payload.usuariosEmpresa,
          observacoes: payload.observacoes,
          createdAt: now,
          updatedAt: now
        }
        
        console.log('🔍 DemandStore.add: Payload filtrado para API:', apiPayload)
        
        try {
          // Tentar criar na API primeiro
          console.log('🔍 DemandStore.add: Enviando para API...')
          const { api } = await import('../lib/api.local')
          const createdDemanda = await api.createDemanda(apiPayload)
          
          console.log('🔍 DemandStore.add: Demanda criada na API:', createdDemanda)
          
          // Mapear resposta da API para o formato do frontend
          const demand: Demand = {
            ...createdDemanda,
            // Manter os IDs originais para edição
            clienteId: payload.clienteId,
            contratoId: payload.contratoId,
            operadoraId: payload.operadoraId,
            produtoId: payload.produtoId,
            sistemaId: payload.sistemaId,
            sistemasIds: payload.sistemasIds,
            areaId: payload.areaId,
            tipoId: payload.tipoId,
            tipoServicoId: payload.tipoServicoId,
            analistaId: payload.analistaId,
            solicitante: payload.solicitante ?? createdDemanda.solicitante,
            qtdUsuarios: payload.qtdUsuarios ?? createdDemanda.qtdUsuarios,
            qtdRetornos: payload.qtdRetornos ?? createdDemanda.qtdRetornos,
            qualidade: payload.qualidade ?? createdDemanda.qualidade,
            qtdClientesVinculados: payload.qtdClientesVinculados ?? createdDemanda.qtdClientesVinculados,
            usuariosEmpresa: payload.usuariosEmpresa ?? createdDemanda.usuariosEmpresa,
            // Garantir que as datas sejam strings
            dataInicio: payload.dataInicio,
            dataFinal: payload.dataFinal,
            createdAt: now,
            updatedAt: now
          }
          
          console.log('🔍 DemandStore.add: Demanda mapeada:', demand)
          
          // Adicionar ao store local
          set((s) => {
            console.log('🔍 DemandStore.add: Adicionando demanda ao store (API):', demand)
            console.log('🔍 DemandStore.add: Items antes:', s.items.length)
            const newItems = [demand, ...s.items]
            console.log('🔍 DemandStore.add: Items depois:', newItems.length)
            return { items: newItems }
          })
          
          // log create
          const { useAuthStore } = await import('./authStore')
          const user = useAuthStore.getState().user
          set((s) => ({ 
            timeline: [
              { 
                id: crypto.randomUUID(), 
                demandaId: demand.id, 
                type: 'create', 
                timestamp: now,
                user: user?.name || 'Usuário desconhecido'
              }, 
              ...s.timeline 
            ] 
          }))
          
          console.log('🔍 DemandStore.add: Demanda adicionada ao store local')
          return demand
          
        } catch (error) {
          console.error('❌ DemandStore.add: Erro ao criar na API:', error)
          console.log('🔍 DemandStore.add: Criando apenas localmente...')
          
          // Fallback: criar apenas localmente
          const demand: Demand = { 
            id: crypto.randomUUID(), 
            createdAt: now, 
            updatedAt: now, 
            ...payload, 
            ticket 
          }
          
          console.log('🔍 DemandStore.add: Demanda local criada:', demand)
          
          // Adicionar ao store local
          set((s) => {
            console.log('🔍 DemandStore.add: Adicionando demanda ao store local:', demand)
            console.log('🔍 DemandStore.add: Items antes:', s.items.length)
            const newItems = [demand, ...s.items]
            console.log('🔍 DemandStore.add: Items depois:', newItems.length)
            return { items: newItems }
          })
          
          // log create
          const { useAuthStore } = await import('./authStore')
          const user = useAuthStore.getState().user
          set((s) => ({ 
            timeline: [
              { 
                id: crypto.randomUUID(), 
                demandaId: demand.id, 
                type: 'create', 
                timestamp: now,
                user: user?.name || 'Usuário desconhecido'
              }, 
              ...s.timeline 
            ] 
          }))
          
          console.log('🔍 DemandStore.add: Demanda criada apenas localmente')
          return demand
        }
      },
      upsert: async (demand) => {
        // 🐛 CORREÇÃO: Normalizar IDs antes de fazer upsert
        const normalizeId = (value: any): string | undefined => {
          if (!value) return undefined
          if (typeof value === 'string') return value
          if (typeof value === 'object' && value !== null) {
            return value.id || value.nome || undefined
          }
          return String(value)
        }
        
        const normalizedDemand: Demand = {
          ...demand,
          analistaId: normalizeId(demand.analistaId),
          areaId: normalizeId(demand.areaId),
          clienteId: normalizeId(demand.clienteId),
          contratoId: normalizeId(demand.contratoId),
          operadoraId: normalizeId(demand.operadoraId),
          produtoId: normalizeId(demand.produtoId),
          sistemaId: normalizeId(demand.sistemaId),
          tipoId: normalizeId(demand.tipoId),
          tipoServicoId: normalizeId(demand.tipoServicoId)
        }
        
        const exists = get().items.some((d) => d.id === normalizedDemand.id)
        
        if (exists) {
          // Atualizar no backend
          try {
            const { api } = await import('../lib/api.local')
            await api.updateDemanda(normalizedDemand.id, normalizedDemand)
            console.log('✅ DemandStore.upsert: Demanda atualizada no backend')
          } catch (error) {
            console.error('❌ DemandStore.upsert: Erro ao atualizar no backend:', error)
            throw error
          }
          
          // Atualizar estado local
          set((s) => ({
            items: s.items.map((d) => (d.id === normalizedDemand.id ? { ...normalizedDemand, updatedAt: new Date().toISOString() } : d))
          }))
        } else {
          // Adicionar novo (usar método add)
          get().add(normalizedDemand)
        }
      },
      remove: async (id) => {
        console.log('🔍 DemandStore: Removendo demanda:', id)
        
        // Remover do estado local imediatamente (otimista)
        set((s) => ({ items: s.items.filter((d) => d.id !== id) }))
        console.log('✅ DemandStore: Demanda removida do estado local')
        
        try {
          // Excluir do backend
          const { useAuthStore } = await import('./authStore')
          const baseUrl = 'https://nigteste-production.up.railway.app'
          const response = await fetch(`${baseUrl}/demandas/${id}`, {
            method: 'DELETE',
            headers: {
              'Authorization': `Bearer ${useAuthStore.getState().token}`,
            },
          })

          if (response.ok) {
            console.log('✅ DemandStore: Demanda excluída do backend:', id)
          } else {
            // Se erro 404, o registro já foi deletado ou não existe - ignorar
            if (response.status === 404) {
              console.log('⚠️ DemandStore: Demanda não encontrada no backend (já foi deletada), continuando...')
              return
            }
            console.error('❌ DemandStore: Erro ao excluir do backend:', response.status)
          }
        } catch (error: any) {
          // Se erro 404, o registro já foi deletado ou não existe - ignorar
          if (error?.statusCode === 404 || error?.message?.includes('404')) {
            console.log('⚠️ DemandStore: Demanda não encontrada no backend, continuando...')
            return
          }
          console.error('⚠️ DemandStore: Erro ao excluir no backend:', error)
        }
      },
      clear: () => set({ items: [], lastSync: 0 }),
      log: async (e) => {
        const eventId = crypto.randomUUID()
        const timestamp = new Date().toISOString()
        const event = { id: eventId, timestamp, ...e }
        
        // Adicionar ao store local imediatamente
        set((s) => ({ timeline: [event, ...s.timeline] }))
        
        // Salvar no banco de dados em background
        try {
          const { api } = await import('../lib/api.local')
          const { useAuthStore } = await import('./authStore')
          const user = useAuthStore.getState().user
          
          await api.createTimelineEvent({
            entityId: e.demandaId!,
            entityType: 'demanda',
            eventType: e.type,
            field: e.field,
            fromValue: e.from,
            toValue: e.to,
            comment: undefined,
            userId: user?.id
          })
          
          console.log('✅ Evento de timeline de demanda salvo no banco:', event)
        } catch (error) {
          console.error('❌ Erro ao salvar evento de timeline no banco:', error)
        }
      },
      async syncFromApi(force?: boolean) {
        const state = get()
        if (state.isLoading) {
          console.log('⏸️ DemandStore: Já está carregando, ignorando chamada duplicada')
          return
        }
        const now = Date.now()
        if (!force && now - state.lastSync < 2 * 60 * 1000) {
          return
        }
        
        // Timeout de segurança para evitar travamento
        const timeoutId = setTimeout(() => {
          console.warn('⚠️ DemandStore: Timeout de 30s atingido, resetando isLoading')
          set({ isLoading: false })
        }, 30000) // 30 segundos
        
        try {
          set({ isLoading: true })
          console.log('🔄 DemandStore: Iniciando syncFromApi...')

          // Importar API dinamicamente
          const { api } = await import('../lib/api.local')

          console.log('🔄 DemandStore: Buscando demandas da API...')
          const demandas = await api.getDemandas()
          console.log(`✅ DemandStore: ${demandas.length} demandas recebidas da API`)
          
          // Limpar timeout se a requisição foi bem-sucedida
          clearTimeout(timeoutId)

          // 🚀 OTIMIZAÇÃO: Normalização otimizada - apenas quando necessário
          const normalizeId = (value: any): string | undefined => {
            if (!value) return undefined
            // Se já é string, retornar diretamente (caso mais comum)
            if (typeof value === 'string') return value
            // Só processar objeto se realmente for objeto
            if (typeof value === 'object' && value !== null) {
              return value.id || value.nome || undefined
            }
            return String(value)
          }
          
          const normalizeName = (value: any): string | undefined => {
            if (!value) return undefined
            // Se já é string, retornar diretamente (caso mais comum)
            if (typeof value === 'string') return value
            // Só processar objeto se realmente for objeto
            if (typeof value === 'object' && value !== null) {
              return value.nome || value.name || value.id || undefined
            }
            return String(value)
          }

          /** ID explícito na coluna OU relação Prisma incluída (objeto com id). Nunca usar string de nome como ID. */
          const idFromColumnOrJoin = (columnId: unknown, relation: unknown): string | undefined => {
            const fromCol = normalizeId(columnId)
            if (fromCol) return fromCol
            if (relation && typeof relation === 'object') return normalizeId(relation)
            return undefined
          }
          
          // 🚀 OTIMIZAÇÃO: Mapeamento otimizado - reduzir chamadas de função
          const demandasMapeadas: Demand[] = demandas.map((d: any) => {
            // Processar IDs uma vez e reutilizar
            const clienteId = idFromColumnOrJoin(d.clienteId, d.cliente)
            const contratoId = idFromColumnOrJoin(d.contratoId, d.contrato)
            const operadoraId = idFromColumnOrJoin(d.operadoraId, d.operadora)
            const produtoId = idFromColumnOrJoin(d.produtoId, d.produto)
            const sistemaId = idFromColumnOrJoin(d.sistemaId, d.sistema)
            const parseSistemasIdsRow = (row: Record<string, unknown>): string[] => {
              const raw = row.sistemasIds
              if (Array.isArray(raw)) return raw.filter((x): x is string => typeof x === 'string')
              return []
            }
            let sistemasIdsRow = parseSistemasIdsRow(d as Record<string, unknown>)
            if (!sistemasIdsRow.length && sistemaId) sistemasIdsRow = [sistemaId]
            const mdSistemas = useMasterDataStore.getState().sistemas
            const sistemaNomeJoined = sistemasIdsRow.length
              ? sistemasIdsRow.map((id) => mdSistemas.find((s) => s.id === id)?.nome || id).join(', ')
              : ''
            const areaId = idFromColumnOrJoin(d.areaId, d.area)
            const tipoId = idFromColumnOrJoin(d.tipoId, d.tipo)
            const tipoServicoId = idFromColumnOrJoin(d.tipoServicoId, d.tipoServico)
            const analistaId = idFromColumnOrJoin(d.analistaId, d.analista)
            
            // Processar nomes apenas se necessário (evitar chamadas duplicadas)
            const analistaName = normalizeName(d.analista)
            const areaName = normalizeName(d.area)
            const clienteName = normalizeName(d.cliente)
            const operadoraName = normalizeName(d.operadora)
            const produtoName = normalizeName(d.produto)
            const sistemaName = sistemaNomeJoined || normalizeName(d.sistema)
            const tipoName = normalizeName(d.tipo)
            const tipoServicoName = normalizeName(d.tipoServico)
            
            return {
              id: d.id,
              ticket: d.ticket,
              status: d.status,
              solicitante: d.solicitante,
              descricao: d.descricao,
              observacoes: d.observacoes,
              qualidade: d.qualidade,
              qtdUsuarios: d.qtdUsuarios ?? (d as { periodicidade?: string }).periodicidade,
              qtdRetornos: d.qtdRetornos,
              qtdClientesVinculados: d.qtdClientesVinculados,
              usuariosEmpresa: d.usuariosEmpresa,
              dataInicio: d.dataInicio,
              dataFinal: d.dataFinal,
              createdAt: d.createdAt,
              updatedAt: d.updatedAt,
              // IDs para edição - já normalizados acima
              clienteId,
              contratoId,
              operadoraId,
              produtoId,
              sistemaId,
              sistemasIds: sistemasIdsRow.length ? sistemasIdsRow : undefined,
              areaId,
              tipoId,
              tipoServicoId,
              analistaId,
              // Campos adicionais - usar nomes já processados ou IDs como fallback
              analista: analistaName || analistaId,
              area: areaName || areaId,
              cliente: clienteName || clienteId,
              operadora: operadoraName || operadoraId,
              produto: produtoName || produtoId,
              sistema: sistemaName || sistemaId,
              tipo: tipoName || tipoId,
              tipoServico: tipoServicoName || tipoServicoId
            } as Demand
          })

          console.log(`✅ DemandStore: ${demandasMapeadas.length} demandas mapeadas, atualizando store...`)
          set({ items: demandasMapeadas, isLoading: false, lastSync: now })
          console.log('✅ DemandStore: syncFromApi concluído com sucesso')
        } catch (error: any) {
          console.error('❌ DemandStore: Erro no syncFromApi:', error)
          console.error('❌ DemandStore: Detalhes do erro:', {
            message: error?.message,
            stack: error?.stack,
            name: error?.name
          })
          // Limpar timeout em caso de erro
          clearTimeout(timeoutId)
          // Garantir que isLoading seja resetado mesmo em caso de erro
          set({ isLoading: false })
        }
      },
      async syncTimeline(demandaId: string) {
        try {
          console.log('🔄 Sincronizando timeline da demanda:', demandaId)
          
          const { api } = await import('../lib/api.local')
          const events = await api.getTimelineEvents(demandaId, 'demanda')
          
          console.log('✅ Timeline sincronizada:', events.length, 'eventos do banco')
          
          // Mapear eventos da API para o formato do frontend
          const mappedEvents = events.map((event: any) => ({
            id: event.id,
            demandaId: event.entityId,
            type: event.eventType,
            field: event.field,
            from: event.fromValue,
            to: event.toValue,
            timestamp: event.createdAt,
            user: event.userName || event.userId || 'Usuário desconhecido'
          }))
          
          // Normalizar valor para comparação (evitar duplicata quando API retorna null e local tem '')
          const norm = (v: unknown): string => (v === null || v === undefined || v === '') ? '' : String(v)

          // Atualizar timeline mesclando eventos do banco com os locais (sem duplicar)
          set((s) => {
            // Manter eventos de outras demandas
            const otherEvents = s.timeline.filter(e => e.demandaId !== demandaId)
            
            // Eventos locais desta demanda
            const localEvents = s.timeline.filter(e => e.demandaId === demandaId)
            
            // Priorizar eventos do banco; incluir local só se não existir no banco
            const mergedEvents = [...mappedEvents]
            
            localEvents.forEach(localEvent => {
              const existsInBank = mappedEvents.some(bankEvent => {
                const timeDiff = Math.abs(new Date(bankEvent.timestamp).getTime() - new Date(localEvent.timestamp).getTime())
                return timeDiff < 15000 &&
                       bankEvent.type === localEvent.type &&
                       bankEvent.field === localEvent.field &&
                       norm(bankEvent.from) === norm(localEvent.from) &&
                       norm(bankEvent.to) === norm(localEvent.to)
              })
              
              if (!existsInBank) {
                mergedEvents.push(localEvent)
              }
            })
            
            return { timeline: [...mergedEvents, ...otherEvents] }
          })
        } catch (error) {
          console.error('❌ Erro ao sincronizar timeline de demanda:', error)
        }
      }
    }),
    {
      name: 'demandStore',
      partialize: (state) => ({ 
        items: state.items, 
        timeline: state.timeline 
      })
    }
  )
)