import { create } from 'zustand'
import { persist } from 'zustand/middleware'
// Removido import de Demand - usando tipo genérico
import type { TimelineEvent } from '../types/timeline'
import { createSafePersistStorage, removeLocalStorageByPrefix } from '../lib/safePersistStorage'
import { hasAuthToken } from '../lib/authSession'
import { useMasterDataStore } from './masterDataStore'
import { shouldSkipStoreSync } from '../utils/syncCooldown'
import {
  loadManutencaoQualificacaoLocal,
} from '../lib/manutencaoQualificacaoStorage'
import { parseManutencaoQualificacao } from '../types/manutencaoQualificacao'

export function clearManutencaoLocalCache(): void {
  removeLocalStorageByPrefix('manutencoes-v')
}

let manutencaoSyncInFlight: Promise<void> | null = null

interface ManutencaoState {
  items: any[]
  timeline: TimelineEvent[]
  isLoading: boolean
  lastSync: number
  add: (d: any) => Promise<any>
  upsert: (d: any) => Promise<void>
  remove: (id: string) => Promise<void>
  clear: () => void
  clearLocal: () => void
  log: (e: Omit<TimelineEvent, 'id' | 'timestamp'>) => void
  syncFromApi: (force?: boolean) => Promise<void>
  syncTimeline: (manutencaoId: string) => Promise<void>
}

export const useManutencaoStore = create<ManutencaoState>()(
  persist(
    (set, get) => ({
      items: [],
      timeline: [],
      isLoading: false,
      lastSync: 0,
      add: async (payload) => {
        console.log('🔍 ManutencaoStore.add: Iniciando criação de manutenção...')
        console.log('🔍 ManutencaoStore.add: Payload recebido:', payload)
        
        function pad(num: number, size: number) {
          let s = String(num)
          while (s.length < size) s = '0' + s
          return s
        }
        
        function generateTicket(existing: any[]): string {
          const now = new Date()
          const y = now.getFullYear()
          const m = pad(now.getMonth() + 1, 2)
          const ym = `${y}${m}`
          const key = `ticket-seq-manutencao-${ym}`
          let seq = 1
          try {
            const raw = localStorage.getItem(key)
            if (raw) seq = Number(raw) + 1
          } catch {}
          // garantir unicidade local
          let ticket = `MAN-${ym}-${pad(seq, 4)}`
          const has = (t: string) => existing.some((d) => (d.ticket || '').toUpperCase() === t.toUpperCase())
          while (has(ticket)) {
            seq += 1
            ticket = `MAN-${ym}-${pad(seq, 4)}`
          }
          localStorage.setItem(key, String(seq))
          return ticket
        }
        
        const now = new Date().toISOString()
        const existing = get().items
        
        // CORRIGIDO: Respeitar o ticket fornecido pelo usuário, ou gerar um novo se não fornecido
        const userProvidedTicket = payload.ticket && payload.ticket.trim() !== ''
        const ticket = userProvidedTicket ? payload.ticket.trim() : generateTicket(existing)
        
        console.log('🎫 TICKET DEBUG (ManutencaoStore):', {
          userInput: payload.ticket,
          userProvidedTicket,
          finalTicket: ticket,
          isAutoGenerated: !userProvidedTicket
        })
        
        const apiPayload = {
          ...payload,
          ticket: ticket, // Usar o ticket determinado
          createdAt: now,
          updatedAt: now
        }
        
        try {
          // Tentar criar na API primeiro
          console.log('🔍 ManutencaoStore.add: Enviando para API...')
          const { api } = await import('../lib/api.local')
          const createdManutencao = await api.createManutencao(apiPayload)
          
          console.log('🔍 ManutencaoStore.add: Manutenção criada na API:', createdManutencao)
          
          // Mapear resposta da API para o formato do frontend
          const manutencao: any = {
            ...createdManutencao,
            // Manter os IDs originais para edição
            clienteId: payload.clienteId,
            contratoId: payload.contratoId,
            contratosIds: (createdManutencao as any)?.contratosIds ?? payload.contratosIds,
            contratosVinculos: (createdManutencao as any)?.contratosVinculos ?? payload.contratosVinculos,
            operadoraId: (createdManutencao as any)?.operadoraId ?? payload.operadoraId,
            produtoId: (createdManutencao as any)?.produtoId ?? payload.produtoId,
            sistemaId: (createdManutencao as any)?.sistemaId ?? payload.sistemaId,
            sistemasIds: (createdManutencao as any)?.sistemasIds ?? payload.sistemasIds,
            sistemasTotais: (createdManutencao as any)?.sistemasTotais ?? payload.sistemasTotais,
            areaId: payload.areaId,
            tipoId: payload.tipoId,
            tipoServicoId: payload.tipoServicoId,
            analistaId: payload.analistaId,
            qualificacaoChamado:
              (createdManutencao as { qualificacaoChamado?: unknown }).qualificacaoChamado ??
              payload.qualificacaoChamado,
            // Garantir que as datas sejam strings
            dataInicio: payload.dataInicio,
            dataFinal: payload.dataFinal,
            createdAt: now,
            updatedAt: now
          }
          
          console.log('🔍 ManutencaoStore.add: Manutenção mapeada:', manutencao)
          
          // Adicionar ao store local
          set((s) => {
            console.log('🔍 ManutencaoStore.add: Adicionando manutenção ao store (API):', manutencao)
            console.log('🔍 ManutencaoStore.add: Items antes:', s.items.length)
            const newItems = [manutencao, ...s.items]
            console.log('🔍 ManutencaoStore.add: Items depois:', newItems.length)
            return { items: newItems }
          })
          
          const { useAuthStore } = await import('./authStore')
          const user = useAuthStore.getState().user
          const displayName = user?.name || user?.email || 'Usuário desconhecido'

          try {
            await api.createTimelineEvent({
              entityId: manutencao.id,
              entityType: 'manutencao',
              eventType: 'create',
              userId: user?.id
            })
          } catch (tlErr) {
            console.warn('⚠️ ManutencaoStore.add: evento create na timeline (servidor):', tlErr)
          }

          set((s) => ({
            timeline: [
              {
                id: crypto.randomUUID(),
                manutencaoId: manutencao.id,
                type: 'create',
                timestamp: now,
                user: displayName
              },
              ...s.timeline
            ]
          }))
          
          console.log('🔍 ManutencaoStore.add: Manutenção adicionada ao store local')
          return manutencao
          
        } catch (error) {
          console.error('❌ ManutencaoStore.add: Erro ao criar na API:', error)
          console.log('🔍 ManutencaoStore.add: Tentando com payload simplificado...')
          
          // Tentar novamente com apenas campos obrigatórios
          try {
            const { api: apiRetry } = await import('../lib/api.local')
            const payloadSimplificado = {
              status: payload.status,
              ticket: payload.ticket,
              tipoServicoId: payload.tipoServicoId,
              tipoId: payload.tipoId,
            }
            
            console.log('🔍 ManutencaoStore.add: Payload simplificado:', payloadSimplificado)
            const manutencao = await apiRetry.createManutencao(payloadSimplificado)
            console.log('🔍 ManutencaoStore.add: Manutenção criada com payload simplificado:', manutencao)
            
            // Adicionar ao store local
            set((s) => {
              const newItems = [manutencao, ...s.items]
              return { items: newItems }
            })

            const { useAuthStore: useAuthStoreRetry } = await import('./authStore')
            const userRetry = useAuthStoreRetry.getState().user
            try {
              await apiRetry.createTimelineEvent({
                entityId: manutencao.id,
                entityType: 'manutencao',
                eventType: 'create',
                userId: userRetry?.id
              })
            } catch (tlErr) {
              console.warn('⚠️ ManutencaoStore.add (retry): timeline create:', tlErr)
            }
            const displayRetry = userRetry?.name || userRetry?.email || 'Usuário desconhecido'
            set((s) => ({
              timeline: [
                {
                  id: crypto.randomUUID(),
                  manutencaoId: manutencao.id,
                  type: 'create',
                  timestamp: now,
                  user: displayRetry
                },
                ...s.timeline
              ]
            }))
            
            console.log('🔍 ManutencaoStore.add: Manutenção criada com sucesso (payload simplificado)')
            return manutencao
            
          } catch (error2) {
            console.error('❌ ManutencaoStore.add: Erro também com payload simplificado:', error2)
            console.log('🔍 ManutencaoStore.add: Criando apenas localmente...')
            
            // Fallback final: criar apenas localmente
            const manutencao: any = { 
              id: crypto.randomUUID(), 
              createdAt: now, 
              updatedAt: now, 
              ...payload, 
              ticket 
            }
            
            console.log('🔍 ManutencaoStore.add: Manutenção local criada:', manutencao)
            
            // Adicionar ao store local
            set((s) => {
              console.log('🔍 ManutencaoStore.add: Adicionando manutenção ao store local:', manutencao)
              console.log('🔍 ManutencaoStore.add: Items antes:', s.items.length)
              const newItems = [manutencao, ...s.items]
              console.log('🔍 ManutencaoStore.add: Items depois:', newItems.length)
              return { items: newItems }
            })
          
          // log create
          const { useAuthStore } = await import('./authStore')
          const user = useAuthStore.getState().user
          set((s) => ({ 
            timeline: [
              { 
                id: crypto.randomUUID(), 
                manutencaoId: manutencao.id, 
                type: 'create', 
                timestamp: now,
                user: user?.name || 'Usuário desconhecido'
              }, 
              ...s.timeline 
            ] 
          }))
          
          console.log('🔍 ManutencaoStore.add: Manutenção criada apenas localmente')
          return manutencao
          }
        }
      },
      upsert: async (manutencao) => {
        const exists = get().items.some((d) => d.id === manutencao.id)
        
        if (exists) {
          // Atualizar no backend
          try {
            const { api } = await import('../lib/api.local')
            await api.updateManutencao(manutencao.id, manutencao)
            console.log('✅ ManutencaoStore.upsert: Manutenção atualizada no backend')
          } catch (error) {
            console.error('❌ ManutencaoStore.upsert: Erro ao atualizar no backend:', error)
            throw error
          }
          
          // Atualizar estado local
          set((s) => ({
            items: s.items.map((d) => (d.id === manutencao.id ? { ...manutencao, updatedAt: new Date().toISOString() } : d))
          }))
        } else {
          // Adicionar novo (usar método add)
          get().add(manutencao)
        }
      },
      remove: async (id) => {
        console.log('🗑️ Removendo manutenção:', id)
        
        // Remover do estado local imediatamente (otimista)
        set((s) => ({ items: s.items.filter((d) => d.id !== id) }))
        console.log('✅ Manutenção removida do estado local')
        
        try {
          // Importar API dinamicamente
          const { api } = await import('../lib/api.local')
          
          // Excluir do backend
          await api.deleteManutencao(id)
          console.log('✅ Manutenção excluída com sucesso no backend')
          
        } catch (error: any) {
          // Se erro 404, o registro já foi deletado ou não existe - ignorar
          if (error?.statusCode === 404) {
            console.log('⚠️ Manutenção não encontrada no backend (já foi deletada), continuando...')
            return
          }
          // Para outros erros, apenas logar
          console.error('⚠️ Erro ao excluir manutenção no backend:', error)
        }
      },
      clear: () => set({ items: [], lastSync: 0 }),
      clearLocal: () => {
        console.log('🔍 ManutencaoStore: Limpando todas as manutenções locais')
        set({ items: [], lastSync: 0 })
        console.log('✅ ManutencaoStore: Manutenções locais limpas')
      },
      log: async (e) => {
        const eventId = crypto.randomUUID()
        const timestamp = new Date().toISOString()
        const event = { id: eventId, timestamp, ...e }
        
        // Adicionar ao store local imediatamente
        set((s) => ({ timeline: [event, ...s.timeline] }))
        
        // Salvar no banco de dados em background
        try {
          const { api } = await import('../lib/api.local')
          const { useAuthStore } = await import('./authStore')
          const user = useAuthStore.getState().user
          
          await api.createTimelineEvent({
            entityId: e.manutencaoId!,
            entityType: 'manutencao',
            eventType: e.type,
            field: e.field,
            fromValue: e.from,
            toValue: e.to,
            comment: undefined,
            userId: user?.id
          })
          
          console.log('✅ Evento de timeline salvo no banco:', event)
        } catch (error) {
          console.error('❌ Erro ao salvar evento de timeline no banco:', error)
          // Não fazer nada - o evento já está salvo localmente
        }
      },
      async syncFromApi(force?: boolean) {
        if (manutencaoSyncInFlight) return manutencaoSyncInFlight

        const state = get()
        const now = Date.now()
        if (shouldSkipStoreSync(state.lastSync, state.items.length, force)) {
          return
        }

        manutencaoSyncInFlight = (async () => {
        try {
          clearManutencaoLocalCache()
          set({ isLoading: true })
          
          // Importar API dinamicamente
          const { api } = await import('../lib/api.local')
          
          const manutencoes = await api.getManutencoes()
          
          // Mapear dados da API para o formato do frontend
          const manutencoesMapeadas: any[] = manutencoes.map((m: any) => {
            const qualificacaoApi = parseManutencaoQualificacao(m.qualificacaoChamado)
            const qualificacaoLocal = loadManutencaoQualificacaoLocal(m.id)
            const qualificacaoChamado =
              qualificacaoApi?.avaliadoEm
                ? qualificacaoApi
                : qualificacaoLocal.avaliadoEm
                  ? qualificacaoLocal
                  : qualificacaoApi ?? undefined

            return {
            id: m.id,
            ticket: m.ticket,
            status: m.status,
            solicitante: m.solicitante,
            descricao: m.descricao,
            observacoes: m.observacoes,
            qualificacaoChamado,
            qualidade: m.qualidade,
            periodicidade: m.periodicidade,
            qtdRetornos: m.qtdRetornos,
            total: m.total,
            sistemasIds: m.sistemasIds,
            sistemasTotais: m.sistemasTotais,
            usuariosEmpresa: m.usuariosEmpresa,
            dataInicio: m.dataInicio,
            dataFinal: m.dataFinal,
            createdAt: m.createdAt,
            updatedAt: m.updatedAt,
            // IDs para edição
            clienteId: m.clienteId,
            contratoId: m.contratoId,
            contratosIds: m.contratosIds,
            contratosVinculos: m.contratosVinculos,
            operadoraId: m.operadoraId,
            produtoId: m.produtoId,
            sistemaId: m.sistemaId,
            areaId: m.areaId,
            tipoId: m.tipoId,
            tipoServicoId: m.tipoServicoId,
            analistaId: m.analistaId,
            // Vínculo ao analista (para filtros/pendências na Home/export)
            analistaObj: m.analista,
            analista: (m.analista?.nome || m.analista?.name || m.analistaId || '') as string,
          }
          })
          
          // Se não há dados da API mas há dados locais, manter os dados locais
          if (manutencoesMapeadas.length === 0 && state.items.length > 0) {
            console.log('🔍 ManutencaoStore: API retornou 0 registros, mantendo dados locais')
            set({ isLoading: false })
            return
          }
          
          set({ items: manutencoesMapeadas, isLoading: false, lastSync: now })
        } catch (error) {
          console.error('❌ ManutencaoStore: Erro no syncFromApi:', error)
          set({ isLoading: false })
        } finally {
          manutencaoSyncInFlight = null
        }
        })()

        return manutencaoSyncInFlight
      },
      async syncTimeline(manutencaoId: string) {
        try {
          console.log('🔄 Sincronizando timeline da manutenção:', manutencaoId)
          
          const { api } = await import('../lib/api.local')
          const events = await api.getTimelineEvents(manutencaoId, 'manutencao')
          
          console.log('✅ Timeline sincronizada:', events.length, 'eventos do banco')
          
          // Mapear eventos da API para o formato do frontend
          const mappedEvents = events.map((event: any) => ({
            id: event.id,
            manutencaoId: event.entityId,
            type: event.eventType,
            field: event.field,
            from: event.fromValue,
            to: event.toValue,
            timestamp: event.createdAt,
            user: event.userName || event.userId || 'Usuário desconhecido'
          }))
          
          // Normalizar valor para comparação (evitar duplicata quando API retorna null e local tem '')
          const norm = (v: unknown): string => (v === null || v === undefined || v === '') ? '' : String(v)

          // Atualizar timeline mesclando eventos do banco com os locais (sem duplicar)
          set((s) => {
            // Manter eventos de outras manutenções
            const otherEvents = s.timeline.filter(e => e.manutencaoId !== manutencaoId)
            
            // Eventos locais desta manutenção
            const localEvents = s.timeline.filter(e => e.manutencaoId === manutencaoId)
            
            // Priorizar apenas eventos do banco (fonte única após sync) para evitar duplicatas
            const mergedEvents = [...mappedEvents]
            
            // Incluir evento local só se não existir no banco (mesmo campo + valores + janela de tempo)
            localEvents.forEach(localEvent => {
              const existsInBank = mappedEvents.some(bankEvent => {
                const timeDiff = Math.abs(new Date(bankEvent.timestamp).getTime() - new Date(localEvent.timestamp).getTime())
                return timeDiff < 15000 && // 15s de tolerância (servidor vs cliente)
                       bankEvent.type === localEvent.type &&
                       bankEvent.field === localEvent.field &&
                       norm(bankEvent.from) === norm(localEvent.from) &&
                       norm(bankEvent.to) === norm(localEvent.to)
              })
              
              if (!existsInBank) {
                mergedEvents.push(localEvent)
              }
            })
            
            return { timeline: [...mergedEvents, ...otherEvents] }
          })
        } catch (error) {
          console.error('❌ Erro ao sincronizar timeline:', error)
        }
      },
    }),
    {
      name: 'manutencoes-v1',
      partialize: (state) => ({ lastSync: state.lastSync }),
      storage: createSafePersistStorage<ManutencaoState>('manutencoes-v1', {
        onQuotaExceeded: clearManutencaoLocalCache,
      }),
      onRehydrateStorage: () => () => {
        queueMicrotask(() => {
          if (!hasAuthToken()) return
          const s = useManutencaoStore.getState()
          if (s.items.length === 0 && !s.isLoading) {
            void s.syncFromApi()
          }
        })
      },
    }
  )
)
