apiVersion: 1

datasources:
  - name: PostgreSQL Demandas
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    database: demandas
    user: postgres
    password: postgres
    isDefault: true
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 15
      timescaledb: false
    secureJsonData:
      password: postgres
